### ISSUE TITLE
Bump nvm-windows Version

### ISSUE THREAD

**Issue by dsanders11** [CircleCI-Public/ansible#203]
There are some important bug fixes in `nvm-windows` 1.1.11, particularly the fix for https://github.com/coreybutler/nvm-windows/issues/955 (which prevents installing the latest Node.js v20 versions). Picking up https://github.com/coreybutler/nvm-windows/pull/709 would also be a nice benefit.

https://github.com/CircleCI-Public/ansible/blob/0c50922f6bf1cae1683ba09d8aec2e7bdb61df54/roles/windows-executor/defaults/main/install_dev_tools_defaults.yml#L13

**Comment by JalexChen** [comment]
hi @dsanders11 - thanks for submitting this issue. it looks like this is in fact installing the wrong nvm package. we should be installing [nvm](https://community.chocolatey.org/packages/nvm) not nvm.portable. 

the choco nvm package points to [nvm.install](https://community.chocolatey.org/packages/nvm.install), which should give you access to the latest versions of node.
